robot_name: "robot_1"
input_topic: "{robot_name}/topic"
input_cert: "/workspaces/amazon-nova-robotic/certificates/{robot_name}/{robot_name}.cert.pem"
input_key: "/workspaces/amazon-nova-robotic/certificates/{robot_name}/{robot_name}.private.key"
input_endpoint: "a1qlex7vqi1791-ats.iot.us-east-1.amazonaws.com"
input_clientId: "arn:aws:iot:us-east-1:111964674713:thing/{robot_name}"
